events {}

http {
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        ssl_certificate /etc/letsencrypt/live/coffeeaurkitaab.co.in/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/coffeeaurkitaab.co.in/privkey.pem;

        location /releases {
            alias /usr/share/nginx/html/releases;
            autoindex on;
        }

        location / {
            proxy_pass http://backend:5000;
        }
    }
}
